federation_version: 2
subgraphs:
  ormi:
    routing_url: https://ormi-graphql.herokuapp.com/
    schema:
      file: './src/sdls/ormi-subgraph.graphql'
  lens:
    routing_url: 'https://api.lens.dev/'
    schema:
      file: './src/sdls/lens.graphql'
  cyberconnect:
    routing_url: 'https://api.cybertino.io/connect/'
    schema:
      file: './src/sdls/cyberconnect.graphql'
