federation_version: 2
subgraphs:
  ormi:
    routing_url: https://ormi-subgraph.herokuapp.com/
    schema:
      file: './src/sdls/ormi-subgraph.graphql'
  ormi:
    routing_url: 'https://api.lens.dev/'
    schema:
      file: './src/sdls/lens.graphql'
  # TODO: obtain correcdt cyberconnect SDL file and enable below
  # cyberconnect:
  #   routing_url: 'https://api.cybertino.io/connect/'
  #   schema:
  #     file: './src/sdls/cyberconnect.graphql'
